polls/urls.py
from django.conf.urls import url, include
from . import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from polls.forms import UserPasswordResetForm

app_name = 'polls'

urlpatterns = [


    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^kaydol/$', views.UserFormView.as_view(), name='register'),
    url(r'^giris/$', views.LoginFormView.as_view(), name='login'),
    url(r'^cikis/$', logoutView, name='logout'),

    #url('', include('django.contrib.auth.urls')),

    url(r'^parola-yenile/$', auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy('polls:password_reset_done'),
            template_name='polls/password_reset_form.html',
            email_template_name='polls/password_reset_email.html',
            subject_template_name='polls/password_reset_subject.txt'),
            name='password_reset'),

    url(r'^parola-yenile/kontrol/$', auth_views.PasswordResetDoneView.as_view(
            template_name='polls/password_reset_done.html'),
            name='password_reset_done'),

    url(r'^yenile/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='polls/password_reset_confirm.html',
            form_class=UserPasswordResetForm,
            success_url = reverse_lazy('polls:password_reset_complete')),
            name='password_reset_confirm'),

    url(r'^yenile/kontrol/$', auth_views.PasswordResetCompleteView.as_view(
            template_name='polls/password_reset_complete.html'),
            name='password_reset_complete'),


    url(r'soru/ekle/$', views.PracticeQuestionsView.as_view(), name='question'),
    url(r'girdi/ekle/(?P<question_slug>[\w-]+)$', input_form, name='input'),

    url(r'dersler$', views.TutorialsView.as_view(), name='tutorial'),
    url(r'dersler/cevapla$', submitTutorialCode, name='submit_subject_code'),
    url(r'dersler/kontrol$', runTutorialCode, name='run_subject_code'),
    url(r'cevapla/gonder$', submitcode, name='submit_code'),
    url(r'cevapla/kontrol$', runCode, name='run_code'),

    url(r'^ara/$', views.SearchDetailsView.as_view(), name='search'),

    url(r'^(?P<slug>[\w-]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<area_slug>[\w-]+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<area_slug>[\w-]+)/(?P<question_slug>[\w-]+)$', views.QuestionExplainView.as_view(), name='question_explain'),


    url(r'dersler/(?P<slug>[\w-]+)$', views.TutorialLectureView.as_view(), name='tutorial_lecture'),
    url(r'dersler/(?P<pk>[0-9]+)/aciklama$', views.SubjectDetailsView.as_view(), name='subject_detail'),

    url(r'profil/duzenle$', views.UserEditView.as_view(), name='edit_profile'),


    url(r'profil/(?P<username>[a-zA-Z0-9]+)$', views.UserView.as_view(), name='hacker'),
    url(r'profil/sorularim/(?P<pk>[0-9]+)/$', views.UserQuestionView.as_view(), name='sorularim'),
    url(r'profil/soru/duzenle/(?P<pk>[0-9]+)/$', views.PracticeQuestionEditView.as_view(), name='question_edit'),
    url(r'profil/soru/sil/(?P<pk>[0-9]+)/$', views.PracticeQuestionDeleteView.as_view(), name='question_delete'),
    url(r'profil/(?P<username>[a-zA-Z0-9]+)/cozulen-problemler/$', views.UserAnswerView.as_view(), name='cozum'),

    url(r'^baglanti/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends')



    #url(r'cevapla/program/derle/$',views.CompileView.as_view(), name='compiler_c')
    #url(r'^(?P<practice_id>[0-9]+)/(?P<area_id>[0-9]+)/$', views.question_area, name='question_area'),
    #url(r'^$', views.dashboard, name='dashboard')
    #url(r'^$', views.post, name='post'),
    #url(r'^$', views.practice, name='practice'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

web_ilk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('polls.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField
from django.template.defaultfilters import slugify
from django.conf import settings


MY_CHOICES = (('c', 'C'),
              ('c++', 'C++'),
              ('c#', 'C#'),
              ('python', 'Python'),
              ('java', 'Java'),
              )

LEVEL_CHOICES = (('kolay', 'KOLAY'),
                 ('orta', 'ORTA'),
                 ('zor', 'ZOR'),
                 ('çok zor', 'ÇOK ZOR'))



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    school = models.CharField(max_length=100, default='')
    point = models.FloatField(default=0)
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    face = models.FileField(default='')
    #solved_questions = models.ManyToManyField(SolvedQuestions)


    @property
    def face_url(self):
        if self.face and hasattr(self.face, 'url'):
            return self.face.url

    #location = models.CharField(max_length=30, blank=True)
    #birth_date = models.DateField(null=True, blank=True)



    def get_absolute_url(self):
        return reverse('polls:hacker', kwargs={'username': self.user.username})


    def __str__(self):  # __unicode__ for Python 2
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])


post_save.connect(create_profile, sender=User)





'''
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    
'''


class Question(models.Model):
    question_text = models.CharField(max_length=20)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=20)
    votes = models.IntegerField(default=0)

class Hacker(models.Model):
    username = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    school = models.CharField(max_length=250)

class tutorial(models.Model):
    tutorial_name = models.CharField(max_length=250)
    tutorial_id = models.CharField(max_length=250)
    tutorial_logo = models.CharField(max_length=250, default='')
    slug = models.SlugField(max_length=40, unique=True, default='')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.tutorial_name.replace('ı', 'i'))
        return super(tutorial, self).save(*args, **kwargs)

    def __str__(self):
        return self.tutorial_name

class tutorial_language(models.Model):
    course = models.ForeignKey(tutorial, on_delete=models.CASCADE)
    language_id = models.CharField(max_length=250)
    language_name = models.CharField(max_length=250)

    def __str__(self):
        return self.language_name



class Tutorial_Lecture(models.Model):
    lecture_discipline = models.ForeignKey(tutorial, on_delete=models.CASCADE)
    lecture_area_name = models.CharField(max_length=100, default='')
    lecture_area_text = RichTextField(max_length=7500, default='')
    lecture_area_input = models.TextField(max_length=150, default='')
    lecture_area_output = models.TextField(max_length=150, default='')


    def get_absolute_url(self):
        return reverse('polls:tutorial_lecture', kwargs={'pk': self.pk})


    def __str__(self):
        return self.lecture_area_name


class Deneme(models.Model):
    deneme_isim = models.CharField(max_length=250)
    deneme_id = models.CharField(max_length=250)


class practice(models.Model):
    practice_name = models.CharField(max_length=250)
    practice_id = models.CharField(max_length=250)
    practice_logo = models.CharField(max_length=250, default='')
    slug = models.SlugField(max_length=40, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.practice_name.replace('ı', 'i'))
        return super(practice, self).save(*args, **kwargs)


    def __str__(self):
        return self.practice_name

class practice_area(models.Model):
    discipline = models.ForeignKey(practice, on_delete=models.CASCADE)
    area_id = models.CharField(max_length=250)
    area_name = models.CharField(max_length=250)
    area_slug = models.SlugField(max_length=260, unique=True, default='')

    def save(self, *args, **kwargs):
        if not self.area_slug:
            self.area_slug = slugify(self.area_name.replace('ı', 'i'))
        return super(practice_area, self).save(*args, **kwargs)

    def get_absolute_url(self, *args, **kwargs):
        return reverse('polls:detail', kwargs={'area_slug': self.area_slug})

    def __str__(self):
        return self.area_name

class practice_question(models.Model):
    practice_discipline = models.ForeignKey(practice_area, on_delete=models.CASCADE, verbose_name='konu adı', null=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, default=1)
    question_area_id = models.CharField(max_length=5, default='1', null=True)
    question_area_name = models.CharField(max_length=100, default='', verbose_name='soru adı')
    question_area_text = RichTextField(max_length=750, default='', verbose_name='soru')
    question_input_text = models.TextField(max_length=150, default='', verbose_name='girdi formatı')
    question_answer_text = models.TextField(max_length=150, default='', verbose_name='çıktı formatı')
    question_language_field = MultiSelectField(choices=MY_CHOICES, default='', verbose_name='kullanılacak diller')
    solved_by_user = models.ManyToManyField(User)
    question_slug = models.SlugField(max_length=110, unique=True, default='', editable=False)
    level = models.CharField(max_length=10, choices=LEVEL_CHOICES, default='kolay')
    point = models.FloatField(default=0)


    def get_unique_slug(self):
        question_slug = slugify(self.question_area_name.replace('ı', 'i'))
        unique_slug = question_slug
        counter = 1
        while practice_question.objects.filter(question_slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(question_slug, counter)
            counter += 1
        return unique_slug


    def save(self, *args, **kwargs):
        if not self.question_slug:
            self.question_slug = self.get_unique_slug()
        return super(practice_question, self).save(*args, **kwargs)


    def get_absolute_url(self, *args, **kwargs):
        return reverse('polls:question_detail', kwargs={'question_slug': self.question_slug})


    def __str__(self):
        return self.question_area_name


class practice_question_input(models.Model):
    input_belong_practice = models.ForeignKey(practice_question, on_delete=models.CASCADE, null=True)
    input_id = models.CharField(max_length=5, default='')
    input_text = models.TextField(max_length=150, default='')
    output_text = models.TextField(max_length=150, default='')


    def get_absolute_url(self):
        return reverse('polls:question')

    def __str__(self):
        return str(self.input_belong_practice)


class SolvedQuestion(models.Model):
    solved_by_user = models.ManyToManyField(UserProfile)
    solved_question_name = models.ForeignKey(practice_question, on_delete=models.CASCADE, null=True)
    solved_question_id = models.CharField(max_length=5, default='')

    def __str__(self):
        return str(self.solved_question_name)


class Friend(models.Model):
    friend_user = models.ManyToManyField(UserProfile)
    current_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='owner', null=True)


    @classmethod
    def add_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.friend_user.add(new_friend)


    @classmethod
    def remove_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.friend_user.remove(new_friend)

    def __str__(self):
        return str(self.current_user)






class challenge(models.Model):
    challenge_name = models.CharField(max_length=250)
    challenge_id = models.CharField(max_length=250)

class Job(models.Model):
    company_name = models.CharField(max_length=250, default='', verbose_name='firma ismi')
    job_name = models.TextField(max_length=100, default='', verbose_name='iş ismi')
    job_description  = RichTextField(max_length=750, default='', verbose_name='iş tanımı')

    def __str__(self):
        return str(self.company_name)

polls/templates/polls/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load staticfiles %}

    <!--<link rel="stylesheet" type="text/css" href="{ static 'polls/stylecss.css' %}"/>-->


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <style>


        @media only screen and (max-width : 990px){

            #myNavbar{
                background-color: #2f393f;
                margin-left: -16px;
                margin-right: -16px;

            }

            .navbar-toggle{
                display: block;
            }

            .dropdown-toggle:active, .open .dropdown-toggle {
                background-color: #2f393f !important;
            }

            .navbar-header {
                float: none;
            }


            .navbar-collapse {
                border-top: 1px solid transparent;
                box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);

            }

            .navbar-collapse.collapse {
                display: none!important;
            }

            .navbar-nav {
                float: none!important;
                margin: 7.5px;

            }

            .navbar-nav >li {
                float: none;
            }

            .navbar-nav >li >a {
                padding-top: 10px;
                padding-bottom: 10px;
            }

            .collapse.in{
                display:block !important;
            }

        }

        body{
            padding-top: 75px;
            background-color: ghostwhite;
        }


        .navbar-inverse{
            height: 50px;
            background-color: #2f393f;
            border-color: #2f393f;
            width: 100%;
        }

        .navbar-inverse .navbar-nav > li {
            margin-bottom: 5px;
            font-size: 13px;
            margin-left: 25px;
        }

        .navbar-inverse .navbar-nav > li > a {
            color: white;

        }

        .navbar-inverse .navbar-header{
            margin-left: 75px;
        }

        .navbar-inverse .navbar-header > a {

            color: white;
            margin-bottom: 15px;

        }


        .navbar-default{
            height: 50px;
            background-color: white;
            border-color: white;
            width: 100%;

        }

        .navbar-default .navbar-nav > li {
            margin-bottom: 5px;
            margin-left: 25px;
            margin-right: 75px;
            font-size: 15px;
            font-weight: bold;

        }


        .navbar-default .navbar-nav > li > a {
            color: skyblue;


        }

        .navbar-default .navbar-header{
            margin-left: 75px;
        }

        .navbar-default .navbar-header > a {
            margin-top: 10px;
            color: steelblue;

        }

        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: white !important;
            background-color: skyblue !important;
        }





        .panel{
            border: 1px solid lightsteelblue;
            border-radius:0;
            transition: box-shadow 0.5s;
            margin-left: 75px;
            margin-top: 30px;
            margin-right: 100px;
            width: 75%;
            background-color: white;

        }

        .panel a h3{
            margin-left: 10px;
            font-size: 21px;
        }

        .panel a button{
            margin-left: 5px;

        }


        .panel:hover {
            box-shadow: 5px 0px 40px rgba(0,0,0, .05);
        }

        .panel-heading {
            color: #fff !important;
            background-color: white !important;
            padding: 25px;
            border-bottom: 1px solid transparent;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }

        .panel .thumbnail {

            padding: 0 0 15px 0;
            border-radius: 0;
            border: none;
            background-color: white;


        }

        .panel .thumbnail img{
            width: 100%;
            height: 250px;

        }



        .panel-footer {
            background-color: whitesmoke !important;

        }

        .panel-footer h3 {
            font-size: 10px;
        }

        .panel-footer h4 {
           choose deepskyblue;
            font-size: 50px;
        }

        .panel-footer .btn {
            margin-top: 30px;
            margin-bottom: 30px;
            background-color: steelblue;
            color: #fff;
        }

        #sidebar-wrapper{
            background: white;
            width: 300px;
            height: 100%;
        }

        #sidebar-wrapper ul{
            color: rgba(230,230,230,0);
            list-style: none;
            padding: 15px 10px;
        }

        #sidebar-wrapper ul li{
            color: #074263;
            padding: 15px 10px;
            margin-left: 60px;
            border-bottom: 1px solid rgba(100,100,100,0.3);

        }

        #sidebar-wrapper ul li a{
            text-decoration: none;
            font-size: 18px;
        }


        #userDropdown{
            margin-right: 85px;

        }

        #userDropdownList{
            padding: 15px;
            margin-right: 85px;
            margin-top: 0;

        }

        #userDropdownList li{
            padding: 10px;
            border-bottom: 1px solid rgba(100,100,100,0.3);

        }

        #userDropdownList li a:hover{
            background: none;
        }

        #footarea{
            background-color: #2f393f;
            height: 75px;
            width: 100%;
            bottom: 0;
            margin-top: 100px;

        }

        #footarea p{
            margin-top: 30px;
            margin-left: 600px;
        }

         .input-group{
            margin-top: 5px;
        }

        #searchButton{
            margin-top: 5px;
            height: 30px;
        }

        #txtSearch{
            margin-top: 5px;
            width: 250px;
            height: 30px;
        }


        #userProfilePanelHeading{
            display: inline-block;
            width: 150px;
            height: 150px;
            border-radius: 50%;
            text-align: center;
            background-image: url("{{ user.userprofile.face_url }}");
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;

        }


        /*#subArea{
            position: absolute;
            margin-top: -133px;
            bottom: 0;
            left: 0;
            right: 0;
            height: 50px;
            clear: both;
            background-color: #187ab2;
        }*/



    </style>

</head>
<body>

    {% if request.user.is_authenticated %}

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href= "#">kodenstitüsü</a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="{% url 'polls:index' %}">
                                <span class="glyphicon glyphicon-home" style="margin-right: 5px"></span>&nbsp;Alıştırmalar
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'polls:tutorial' %}">
                                <span class="glyphicon glyphicon-book" style="margin-right: 5px"></span>&nbsp;Dersler
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <span class="glyphicon glyphicon-time" style="margin-right: 5px"></span>&nbsp;Yarışmalar
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <span class="glyphicon glyphicon-briefcase" style="margin-right: 5px"></span>&nbsp;İş
                            </a>
                        </li>

                        <li>

                            <form class="form-inline" action="{% url 'polls:search' %}" method="GET">

                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Ara" name="searchname" id="txtSearch"/>
                                <div class="input-group-btn">
                                    <button id="searchButton" class="btn btn-primary" type="submit">
                                        <span id="searchIconArea" class="glyphicon glyphicon-search"></span>
                                    </button>
                                </div>
                            </div>

                        </form>


                        </li>



                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" id="userDropdown" class="dropdown-toggle" data-toggle="dropdown">
                                {{ request.user.username }}
                                <span class="glyphicon glyphicon-triangle-bottom" style="margin-right: 15px"></span>
                            </a>
                            <ul class="dropdown-menu" id="userDropdownList">
                                <li>
                                    <a href="{% url 'polls:hacker' request.user.username %}">
                                        <span class="glyphicon glyphicon-user" style="margin-right: 5px"></span>&nbsp;Kullanıcı Profili
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'polls:question' %}">
                                        <span class="glyphicon glyphicon-plus" style="margin-right: 5px"></span>&nbsp;Soru Ekle
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'polls:edit_profile' %}">
                                        <span  class="glyphicon glyphicon-wrench" style="margin-right: 5px"></span>&nbsp;Profili Düzenle
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'polls:logout' %}">
                                        <span class="glyphicon glyphicon-off" style="margin-right: 5px"></span>&nbsp;Oturumu Kapat
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

    {% endif %}

    {% if not request.user.is_authenticated %}

        <nav class="navbar navbar-default bg-primary navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href= "#">WebSiteName</a>
                </div>
                <div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="" style="margin-right: 0">
                            <a href="{% url 'polls:login' %}">
                                <span aria-hidden="true"></span>&nbsp;Giriş Yap
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'polls:register' %}">
                                <span aria-hidden="true"></span>Kaydol
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    {% endif %}

    {% block body %}


    {% endblock %}
</body>

<footer>
     <div id="footarea" class="col-md-12 col-sm-12">
         <p style="color: white">Tüm hakları saklıdır</p>
     </div>
</footer>

</html>

polls/templates/polls/password_reset_complete.html
{% extends 'polls/base.html' %}

{% block body %}

    <p>
        Parola başarıyla değiştirildi. Şu anda <a href="{% url 'polls:login' %}">giriş yap</a> kısmından
        giriş yapabilirsiniz.
    </p>

{% endblock %}

polls/templates/polls/user_profile.html
{% extends 'polls/base.html' %}



{% block body %}

    <div class="col-sm-4">

        <div class="container" style="margin-top: 50px; margin-left: 75px; width: 300px; background-color: white">


            <div class="panel panel-heading" id="userProfilePanelHeading">
                <!--img src="{#  #}{ user.userprofile.face_url|default_if_none:'static/media/AdaLovelace.png' }}"-->
            </div>

            {% if not profile_user|safe in friend_list|safeseq and profile_user|safe != user.userprofile|safe %}
            <a class="btn btn-primary" style="width: 250px; font-weight: bold;
                       font-size: medium; text-align: center; margin-left: 15px"
                           href="{% url 'polls:change_friends' operation='ekle' pk=user.pk%}">
                            Bağlantı Kur
            </a>
            {% endif %}

            <hr style="width: 250px">

            <h4>Adı</h4>
            <h5 style="font-weight: bold">{{ user.userprofile.name }}</h5>
            <hr style="width: 200px">

            <h4>Kullanıcı adı</h4>
            <h5 style="font-weight: bold">{{ user.username }}</h5>
            <hr style="width: 200px">

            <h4>Okul</h4>
            <h5 style="font-weight: bold">{{ user.userprofile.school }}</h5>
            <hr style="width: 200px">

            <h4>Web sitesi</h4>
            <h5 style="font-weight: bold">{{ user.userprofile.website }}</h5>
            <hr style="width: 200px">






        </div>



    </div>


    <div class="col-sm-5" style="padding: 50px 50px;">

        <div class="container" style="width: 75%; margin-left: 0; background-color: white">


            <h3 style="font-weight: bold; color: #2D2D2D">Toplam Puan : {{ user.userprofile.point }}</h3>
            <br>

            <h3 style="font-weight: bold; color: #2D2D2D">Seviye :</h3>
            <br>
            <br>
            <br>

            <a class="btn btn-info" style="width: 300px; font-weight: bold;
            font-size: medium" href="{% url 'polls:sorularim' user.pk %}">Alınan Dersler</a>
            <br>
            <br>
            <br>

            <a class="btn btn-primary" style="width: 300px; font-size: medium; font-weight: bold" href="{% url 'polls:sorularim' user.pk %}">Sorulan Sorular</a>
            <br>
            <br>
            <br>

            <a class="btn btn-success" style="width: 300px; font-size: medium; font-weight: bold" href="{% url 'polls:cozum' user.username %}">Çözülen Problemler</a>
            <br>
            <br>
            <br>


            {#% for users_item in friend_list %#}
                {#  #}
            {#% endfor %#}




        </div>


    </div>

    <div class="col-sm-offset-7" style="padding: 50px 50px">
        <div class="container" style="background-color: white; width: 75%; height: auto">

            <h2 style="font-family: 'Times New Roman', bold,monospace">Bağlantılar</h2>
            <hr style="width: 320px">

            {% for friend_item in user.userprofile.friend_set.all %}
                <a style="width: 300px; font-size: medium; font-weight: bold" href="{% url 'polls:hacker' friend_item %}">{{ friend_item }}</a>

                <br>
                <br>
            {% endfor %}

        </div>
    </div>

{% endblock %}